#!/bin/sh
#
# $Id: bootstrap 100 2007-06-28 14:49:29Z flovergine $
#
# Copyright (C) 2004,2007 Francesco P. Lovergine <frankie@yardradius.org>
# All rights reserved. See LICENSE file for license information.
#
# This script is useful on Debian GNU/Linux as an alternative to autoreconf.
# Adaptable to other platforms mutata mutanda.
#

autoheader \
&& aclocal \
&& autoconf \
&& automake --add-missing --force --copy 
